### PR TITLE
Add Event Pump; Closes #9

### LINKED ISSUE #9: Create EventPump to Drive Simulation Library
The simulation library needs a mechanism to drive its update function. A angular service should be created to allow components to register a callback to be executed at a given rate. This service should be able to pause and resume.

### PR DESCRIPTION
**Pull request by benjic**
Problem
-------

There is no central mechanism to link animation and simulation. There is no
central loop that can drive the simulation library.

Solution
--------

Create a service which produces a singleton that executes a set of callbacks on
each animation frame. This provides a consistent mechanism for the simulation
and controls to interact with the flow of the program.

Areas of Impact
---------------

This refactors the file structure of the program. This will cause grief for any
pending progress. We can hash out how to merge this.

Howto Test
----------

- [ ] Open the application
- [ ] Notice the FPS counter directive showing the current state and FPS
- [ ] Click the pause and resume to interact with the eventPump service
- [ ] Notice the state and FPS change with the eventPump state.

References
----------

- /cc @mkinsey @aaroncameron21
- [GH Issue](https://github.com/orbitable/bridge/issues/9)

### CODE REVIEW

**Comment by aaroncameron21** [comment]
I looked through the code and have an idea of how it works, but when I tried to test it, I couldn't see the FPS counter or see the pause/play buttons having any effect.

**Comment by mkinsey** [comment]
I think that this provides some much needed structure and integration to our app. I was able to get test it and it is behaving as expected. Big thanks to Ben for making it happen! I think we should merge and sort the conflicts out on issue branches. 

@alexander-dunn how will this impact you? 

@aaroncameron21 did you try the instructions in the [read me](https://github.com/orbitable/bridge/blob/master/README.md)  to get the app up and running?

**Comment by benjic** [comment]
It may be easier to merge what is in progress and let me sort out the conflicts since there are changes in the file structure.

**Comment by benjic** [comment]
@aaroncameron21 Was there any console errors?

**Comment by aaroncameron21** [comment]
@mkinsey was right, I forgot to install the stuff in the read me into the cloned folder. I'll try it out again once I'm home, but I'm sure it will work. I'll go ahead and merge it.

**Pull request merged**
